<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.22621.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RuntimeIdentifier>win-arm64</RuntimeIdentifier>
    <PlatformTarget>ARM64</PlatformTarget>
    <AssemblyName>Rpi5FanControl</AssemblyName>
    <RootNamespace>Rpi5FanControl</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\fan.ico</ApplicationIcon>
    <Version>0.1.1-exp.6.1</Version>
    <FileVersion>0.1.1.61</FileVersion>
    <AssemblyVersion>0.1.1.61</AssemblyVersion>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="Assets\fan.png" />
    <Resource Include="Assets\fan.ico" />
  </ItemGroup>
</Project>
